language: node_js

branches:
  only:
    - master

script:
  - npm run lint
  - npm run test-headless
  - npm run build-github

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
