language: node_js
node_js:
  - node

branches:
  only:
    - master

script:
  - npm run lint
  - npm run test-headless
  - npm run build-github

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/mettscape
  on:
    branch: master
